CREATE DATABASE IF NOT EXISTS reclamations CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE reclamations;

CREATE TABLE IF NOT EXISTS reclamations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  objet VARCHAR(255) NOT NULL,
  reclamation TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
